@startuml
hide methods
hide stereotypes

class exercises {
  id
  name
}

class workouts {
  id
  user_id
  started_at
}

class workout_exercises {
  id
  workout_id
  exercise_id
  order_index
}

class sets {
  id
  workout_exercise_id
  reps
  weight
}

class personal_records {
  id
  user_id
  exercise_id
  pr_type
  value
}

workouts -- workout_exercises
exercises -- workout_exercises
workout_exercises -- sets
exercises -- personal_records
@enduml
